/// A review item generated by weather rules. This type has no activation path.
enum WeatherSuggestionState { suggested }

final class WeatherSuggestion {
  WeatherSuggestion({
    required this.id,
    required this.sourceSnapshotId,
    required this.ruleId,
    required List<String> recommendedTemplateIds,
    required this.createdAt,
  }) : recommendedTemplateIds = List.unmodifiable(recommendedTemplateIds);

  /// Deterministic ID makes repeating the same snapshot/rule evaluation replay-safe.
  final String id;
  final String sourceSnapshotId;
  final String ruleId;
  final List<String> recommendedTemplateIds;
  final DateTime createdAt;

  String get source => 'BMKG';
  WeatherSuggestionState get state => WeatherSuggestionState.suggested;
}
